# Generated by Django 5.1.3 on 2025-01-18 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole_buxton_be', '0002_product_category_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pictures',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cole_buxton_be.product')),
            ],
            options={
                'db_table': 'cb_product_image',
            },
        ),
    ]
