# Generated by Django 5.1.3 on 2025-01-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole_buxton_be', '0003_remove_product_pictures_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
