# Generated by Django 5.1.3 on 2025-01-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole_buxton_be', '0004_product_details_product_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'cb_cart_item',
            },
        ),
    ]
