# Generated by Django 5.1.3 on 2025-01-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole_buxton_be', '0005_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='color',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
