# Generated by Django 5.1.3 on 2025-01-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole_buxton_be', '0006_rename_color_cartitem_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
