# Generated by Django 5.1.3 on 2025-01-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cole_buxton_be', '0009_alter_cartitem_size_productsize'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productsize',
            table='cb_product_size',
        ),
    ]
