# Generated by Django 5.1.3 on 2025-01-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole_buxton_be', '0011_alter_productsize_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(choices=[('new-launches', 'New Launches'), ('anniversary-drop', 'Anniversary Drop'), ('footwear', 'Footwear')], default='footwear', max_length=100),
        ),
    ]
