# Generated by Django 5.1.3 on 2025-01-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cole_buxton_be', '0012_remove_product_category_product_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='products_group',
            field=models.CharField(default='', max_length=100),
        ),
    ]
