# Generated by Django 5.1.3 on 2025-01-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cole_buxton_be', '0013_productimage_products_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='products_group',
            new_name='product_code',
        ),
    ]
