# Generated by Django 5.1.3 on 2025-02-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cole_buxton_be', '0014_rename_products_group_productimage_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product_code',
        ),
    ]
