# Generated by Django 5.1.3 on 2025-02-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cole_buxton_be', '0015_rename_product_id_cartitem_product_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='full_name',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product_code',
        ),
    ]
