# Generated by Django 5.1.3 on 2025-02-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cole_buxton_be', '0017_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='url',
        ),
    ]
